### ISSUE TITLE
yolov5.cpp中的nms问题

### ISSUE THREAD

**Issue by ABCAI93** [a954217436/yolov5s_ncnn_inference#1]
非常感谢代码的分享。
我看了下源码，对yolov5.cpp文件中的nms有点疑问，nonMaxSuppression中过滤掉重复框的时候好像没判断是否是同一个类别，只通过判断了iou的阈值，还麻烦检查一下是否是代码有误。

**Comment by sean-wade** [comment]
nms可以根据类别来区分，也可以把所有目标当做一个类别来做，这个你可以自己实现下~ 我认为不算错误哈，仅是实现方式有所区别
